# Generated by Django 5.1 on 2024-08-15 16:08

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to=shop.models.books_image_file_path)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Embroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOY', 'Boy'), ('GIRL', 'Girl')], max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl')], max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to=shop.models.embroidery_image_file_path)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(blank=True, to='shop.book')),
                ('embroideries', models.ManyToManyField(blank=True, to='shop.embroidery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
