# Generated by Django 5.1 on 2024-08-20 12:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embroidery',
            name='size',
        ),
        migrations.AddField(
            model_name='embroidery',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
