# Generated by Django 5.1 on 2024-08-27 08:51

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_embroidery_size_embroidery_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.books_image_file_path)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.book')),
            ],
        ),
        migrations.CreateModel(
            name='EmbroideryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.embroidery_image_file_path)),
                ('embroidery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.embroidery')),
            ],
        ),
    ]
