# Generated by Django 5.1 on 2024-08-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bookimage_embroideryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookimage',
            old_name='book',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='embroideryimage',
            old_name='embroidery',
            new_name='name',
        ),
    ]
