# Generated by Django 5.1 on 2024-08-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_book_bookimage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='embroidery',
            name='image',
        ),
    ]
