# Generated by Django 5.1 on 2024-08-30 09:44

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_book_image_remove_embroidery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.books_image_file_path),
        ),
        migrations.AddField(
            model_name='embroidery',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.books_image_file_path),
        ),
    ]
