# Generated by Django 5.1 on 2024-08-30 09:51

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_book_image_embroidery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.book'),
        ),
        migrations.AlterField(
            model_name='embroidery',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.embroidery_image_file_path),
        ),
        migrations.AlterField(
            model_name='embroideryimage',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.embroidery'),
        ),
    ]
